# diagnose-failure.ps1
# Project 7: Break It on Purpose
#
# This script diagnoses the most recent failure using ONLY:
#   1. logs\loop.log
#   2. progress.md
#
# It does NOT re-run morning-brief.ps1, does NOT read source-data.txt,
# and does NOT replay the failed run in any way. This mirrors a real
# unattended loop failing overnight: the log and the spine are all you
# get, so the diagnosis must come from them alone.

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$LogPath = Join-Path $ProjectRoot "logs\loop.log"
$ProgressPath = Join-Path $ProjectRoot "progress.md"
$ReportPath = Join-Path $ProjectRoot "reports\diagnosis-report.md"

if (-not (Test-Path $LogPath)) {
    Write-Host "[MISSING] logs\loop.log - cannot diagnose without it."
    exit 1
}

if (-not (Test-Path $ProgressPath)) {
    Write-Host "[MISSING] progress.md - cannot diagnose without it."
    exit 1
}

$LogLines = Get-Content $LogPath
$ProgressText = Get-Content $ProgressPath -Raw

# Find every real run line (skip comment lines starting with #)
$RunLines = $LogLines | Where-Object { $_ -and ($_ -notmatch "^#") }

if ($RunLines.Count -eq 0) {
    Write-Host "No run entries found in logs\loop.log yet. Run morning-brief.ps1 or sabotage-loop.ps1 first."
    exit 1
}

# Parse each run line into a simple lookup table of KEY = VALUE
function Parse-LogLine {
    param([string]$Line)

    $Fields = @{}
    $Parts = $Line -split "\|"
    foreach ($Part in $Parts) {
        $Trimmed = $Part.Trim()
        $EqualIndex = $Trimmed.IndexOf("=")
        if ($EqualIndex -gt 0) {
            $Key = $Trimmed.Substring(0, $EqualIndex).Trim()
            $Value = $Trimmed.Substring($EqualIndex + 1).Trim()
            $Fields[$Key] = $Value
        }
    }
    return $Fields
}

$ParsedRuns = @()
foreach ($Line in $RunLines) {
    $ParsedRuns += Parse-LogLine -Line $Line
}

$LastRun = $ParsedRuns[$ParsedRuns.Count - 1]

# Find the most recent FAILED run specifically (may be same as LastRun)
$FailedRuns = $ParsedRuns | Where-Object { $_["STATUS"] -eq "FAILED" }
$LastFailedRun = $null
if ($FailedRuns.Count -gt 0) {
    $LastFailedRun = $FailedRuns[$FailedRuns.Count - 1]
}

# Build the answers
if ($LastFailedRun -ne $null) {
    $WhatFailed = "Run " + $LastFailedRun["RUN_ID"] + " (mode " + $LastFailedRun["MODE"] + ") failed."
    $WhenFailed = $LastFailedRun["TIMESTAMP"]
    $WhichAttempt = $LastFailedRun["ATTEMPT"] + " of " + $LastFailedRun["MAX_ATTEMPTS"]
    $FailureReason = $LastFailedRun["REASON"]
    $MaxReached = "NO"
    if ($LastFailedRun["ATTEMPT"] -eq $LastFailedRun["MAX_ATTEMPTS"]) {
        $MaxReached = "YES"
    }
    $NeedsHumanFromLog = $LastFailedRun["NEEDS_HUMAN"]
    $Observable = "YES - the failure is fully described by RUN_ID, TIMESTAMP, ATTEMPT, STATUS, NEEDS_HUMAN, and REASON fields in logs\loop.log."
}
else {
    $WhatFailed = "No failed runs were found in logs\loop.log. The most recent run succeeded."
    $WhenFailed = $LastRun["TIMESTAMP"]
    $WhichAttempt = $LastRun["ATTEMPT"] + " of " + $LastRun["MAX_ATTEMPTS"]
    $FailureReason = "None"
    $MaxReached = "N/A"
    $NeedsHumanFromLog = $LastRun["NEEDS_HUMAN"]
    $Observable = "YES - the log clearly shows a SUCCESS status with no failure fields set."
}

$NeedsHumanFromProgress = "UNKNOWN"
if ($ProgressText -match "Needs human:\s*(\S+)") {
    $NeedsHumanFromProgress = $Matches[1]
}

$NextActionFromProgress = "UNKNOWN"
if ($ProgressText -match "Next action:\s*(.+)") {
    $NextActionFromProgress = $Matches[1].Trim()
}

$RequestedHumanClearly = "NO"
if ($NeedsHumanFromLog -eq "YES" -or $NeedsHumanFromProgress -eq "YES") {
    $RequestedHumanClearly = "YES"
}

# Build the report
$ReportLines = @()
$ReportLines += "# Diagnosis Report - Project 7 Break It on Purpose"
$ReportLines += ""
$ReportLines += "Generated by scripts\diagnose-failure.ps1 using ONLY logs\loop.log"
$ReportLines += "and progress.md. No run was replayed and source-data.txt was not read."
$ReportLines += ""
$ReportLines += "## 1. What failed?"
$ReportLines += $WhatFailed
$ReportLines += ""
$ReportLines += "## 2. When did it fail?"
$ReportLines += $WhenFailed
$ReportLines += ""
$ReportLines += "## 3. Which attempt failed?"
$ReportLines += $WhichAttempt
$ReportLines += ""
$ReportLines += "## 4. What was the failure reason?"
$ReportLines += $FailureReason
$ReportLines += ""
$ReportLines += "## 5. Was the maximum attempt limit reached?"
$ReportLines += $MaxReached
$ReportLines += ""
$ReportLines += "## 6. Did the loop clearly request human intervention?"
$ReportLines += ("From log: " + $NeedsHumanFromLog)
$ReportLines += ("From progress.md: " + $NeedsHumanFromProgress)
$ReportLines += ("Overall: " + $RequestedHumanClearly)
$ReportLines += ""
$ReportLines += "## 7. Was the failure observable?"
$ReportLines += $Observable
$ReportLines += ""
$ReportLines += "## 8. What should a human do next?"
$ReportLines += $NextActionFromProgress
$ReportLines += ""
$ReportLines += "---"
$ReportLines += "This report was built entirely from the spine (progress.md) and the"
$ReportLines += "log (logs\loop.log). This is the same information you would have if"
$ReportLines += "this loop had failed overnight with nobody watching."

Set-Content -Path $ReportPath -Value $ReportLines

Write-Host "Diagnosis complete. Report written to reports\diagnosis-report.md"
Write-Host ""
Get-Content $ReportPath