# estimate-cost.ps1
# Project 7: Break It on Purpose
#
# This script estimates the monthly token usage and monthly dollar cost
# of a loop, using Concept 13's math: tokens per beat, multiplied by
# how often the loop fires (its cadence), projected across 30 days.
#
# All prices you enter are YOUR OWN estimates. This script does not
# know or assume any real, current provider pricing. Nothing here calls
# the network or any AI model.

function Read-NumberOrDefault {
    param(
        [string]$Prompt,
        [double]$Default
    )

    $Input = Read-Host ($Prompt + " (default " + $Default + ")")
    if ([string]::IsNullOrWhiteSpace($Input)) {
        return $Default
    }

    $Parsed = 0.0
    $Success = [double]::TryParse($Input, [ref]$Parsed)
    if ($Success) {
        return $Parsed
    }
    else {
        Write-Host "Could not read that as a number. Using default: $Default"
        return $Default
    }
}

Write-Host "=========================================================="
Write-Host " Monthly Cost Estimate (Concept 13) - all values are ESTIMATES"
Write-Host "=========================================================="

$InputTokensPerBeat = Read-NumberOrDefault -Prompt "Approximate INPUT tokens per beat (one run)" -Default 1500
$OutputTokensPerBeat = Read-NumberOrDefault -Prompt "Approximate OUTPUT tokens per beat (one run)" -Default 400
$RunsPerDay = Read-NumberOrDefault -Prompt "Runs per day" -Default 1
$InputPricePerMillion = Read-NumberOrDefault -Prompt "Your estimated INPUT price per 1,000,000 tokens (in your currency)" -Default 3.0
$OutputPricePerMillion = Read-NumberOrDefault -Prompt "Your estimated OUTPUT price per 1,000,000 tokens (in your currency)" -Default 15.0

$DaysPerMonth = 30

$MonthlyRuns = $RunsPerDay * $DaysPerMonth
$MonthlyInputTokens = $InputTokensPerBeat * $MonthlyRuns
$MonthlyOutputTokens = $OutputTokensPerBeat * $MonthlyRuns
$MonthlyTotalTokens = $MonthlyInputTokens + $MonthlyOutputTokens

$MonthlyInputCost = ($MonthlyInputTokens / 1000000) * $InputPricePerMillion
$MonthlyOutputCost = ($MonthlyOutputTokens / 1000000) * $OutputPricePerMillion
$MonthlyTotalCost = $MonthlyInputCost + $MonthlyOutputCost

Write-Host ""
Write-Host "=========================================================="
Write-Host " ESTIMATE RESULTS (30-day month, all figures are estimates)"
Write-Host "=========================================================="
Write-Host ("Runs per month:            " + $MonthlyRuns)
Write-Host ("Monthly input tokens:      " + $MonthlyInputTokens)
Write-Host ("Monthly output tokens:     " + $MonthlyOutputTokens)
Write-Host ("Monthly total tokens:      " + $MonthlyTotalTokens)
Write-Host ("Estimated monthly input cost:   " + [Math]::Round($MonthlyInputCost, 4))
Write-Host ("Estimated monthly output cost:  " + [Math]::Round($MonthlyOutputCost, 4))
Write-Host ("Estimated monthly TOTAL cost:   " + [Math]::Round($MonthlyTotalCost, 4))
Write-Host "=========================================================="

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$ReportPath = Join-Path $ProjectRoot "reports\cost-report.md"

$ReportLines = @()
$ReportLines += "# Cost Report - Project 7 Break It on Purpose"
$ReportLines += ""
$ReportLines += "Generated by scripts\estimate-cost.ps1. ALL VALUES BELOW ARE"
$ReportLines += "ESTIMATES entered by the user, not real current provider pricing."
$ReportLines += ""
$ReportLines += "## Inputs"
$ReportLines += ("Input tokens per beat: " + $InputTokensPerBeat)
$ReportLines += ("Output tokens per beat: " + $OutputTokensPerBeat)
$ReportLines += ("Runs per day: " + $RunsPerDay)
$ReportLines += ("Input price per 1,000,000 tokens (estimate): " + $InputPricePerMillion)
$ReportLines += ("Output price per 1,000,000 tokens (estimate): " + $OutputPricePerMillion)
$ReportLines += ("Days per month used for this estimate: " + $DaysPerMonth)
$ReportLines += ""
$ReportLines += "## Results (estimates)"
$ReportLines += ("Runs per month: " + $MonthlyRuns)
$ReportLines += ("Monthly input tokens: " + $MonthlyInputTokens)
$ReportLines += ("Monthly output tokens: " + $MonthlyOutputTokens)
$ReportLines += ("Monthly total tokens: " + $MonthlyTotalTokens)
$ReportLines += ("Estimated monthly input cost: " + [Math]::Round($MonthlyInputCost, 4))
$ReportLines += ("Estimated monthly output cost: " + [Math]::Round($MonthlyOutputCost, 4))
$ReportLines += ("Estimated monthly TOTAL cost: " + [Math]::Round($MonthlyTotalCost, 4))

Set-Content -Path $ReportPath -Value $ReportLines

Write-Host ""
Write-Host "Saved to reports\cost-report.md"