# diagnose-failure.ps1
# Project 8: Your Own Daily Loop
#
# Diagnoses the most recent failure using ONLY:
#   1. progress.md
#   2. logs\loop.log
#   3. the existing files in reports\ (as they currently stand)
#
# It does NOT re-run scripts\daily-loop.ps1 and does NOT read
# source-data.txt to guess what should have happened.

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$LogPath = Join-Path $ProjectRoot "logs\loop.log"
$ProgressPath = Join-Path $ProjectRoot "progress.md"
$ReviewerReportPath = Join-Path $ProjectRoot "reports\reviewer-report.md"
$AuditReportPath = Join-Path $ProjectRoot "reports\dependency-audit.md"
$DiagnosisReportPath = Join-Path $ProjectRoot "reports\diagnosis-report.md"

if (-not (Test-Path $LogPath)) {
    Write-Host "[MISSING] logs\loop.log - cannot diagnose without it."
    exit 1
}

if (-not (Test-Path $ProgressPath)) {
    Write-Host "[MISSING] progress.md - cannot diagnose without it."
    exit 1
}

$LogLines = Get-Content $LogPath
$ProgressText = Get-Content $ProgressPath -Raw

$RunLines = $LogLines | Where-Object { $_ -and ($_ -notmatch "^#") }

if ($RunLines.Count -eq 0) {
    Write-Host "No run entries found in logs\loop.log yet. Run scripts\daily-loop.ps1 first."
    exit 1
}

function Parse-LogLine {
    param([string]$Line)

    $Fields = @{}
    $Parts = $Line -split "\|"
    foreach ($Part in $Parts) {
        $Trimmed = $Part.Trim()
        $EqualIndex = $Trimmed.IndexOf("=")
        if ($EqualIndex -gt 0) {
            $Key = $Trimmed.Substring(0, $EqualIndex).Trim()
            $Value = $Trimmed.Substring($EqualIndex + 1).Trim()
            $Fields[$Key] = $Value
        }
    }
    return $Fields
}

$ParsedRuns = @()
foreach ($Line in $RunLines) {
    $ParsedRuns += Parse-LogLine -Line $Line
}

$LastRun = $ParsedRuns[$ParsedRuns.Count - 1]

$ProblemRuns = $ParsedRuns | Where-Object {
    ($_["MAKER_STATUS"] -eq "FAILED") -or
    ($_["REVIEWER_VERDICT"] -eq "FAIL") -or
    ($_["BUDGET_STATUS"] -eq "EXCEEDED")
}

$LastProblemRun = $null
if ($ProblemRuns.Count -gt 0) {
    $LastProblemRun = $ProblemRuns[$ProblemRuns.Count - 1]
}

if ($LastProblemRun -ne $null) {
    $WhatFailed = "Run " + $LastProblemRun["RUN_ID"] + " had a problem."
    $WhenFailed = $LastProblemRun["TIMESTAMP"]

    $WhyParts = @()
    if ($LastProblemRun["MAKER_STATUS"] -eq "FAILED") {
        $WhyParts += "the implementer (maker) failed"
    }
    if ($LastProblemRun["REVIEWER_VERDICT"] -eq "FAIL") {
        $WhyParts += "the reviewer (checker) returned FAIL"
    }
    if ($LastProblemRun["BUDGET_STATUS"] -eq "EXCEEDED") {
        $WhyParts += "the daily budget limit was exceeded"
    }
    $WhyFailed = [string]::Join(", ", $WhyParts)
    $ReasonField = $LastProblemRun["REASON"]
    $NeedsHumanFromLog = $LastProblemRun["NEEDS_HUMAN"]
}
else {
    $WhatFailed = "No failed or FAIL/EXCEEDED runs were found. The most recent run succeeded."
    $WhenFailed = $LastRun["TIMESTAMP"]
    $WhyFailed = "N/A"
    $ReasonField = "None"
    $NeedsHumanFromLog = $LastRun["NEEDS_HUMAN"]
}

$NeedsHumanFromProgress = "UNKNOWN"
if ($ProgressText -match "Needs Human:\s*(\S+)") {
    $NeedsHumanFromProgress = $Matches[1]
}

$NextActionFromProgress = "UNKNOWN"
if ($ProgressText -match "Next action:\s*(.+)") {
    $NextActionFromProgress = $Matches[1].Trim()
}

$RequiresHuman = "NO"
if ($NeedsHumanFromLog -eq "YES" -or $NeedsHumanFromProgress -eq "YES") {
    $RequiresHuman = "YES"
}

$ReviewerNote = "reports\reviewer-report.md was not found."
if (Test-Path $ReviewerReportPath) {
    $ReviewerText = Get-Content $ReviewerReportPath -Raw
    if ($ReviewerText -match "Verdict:\s*(\S+)") {
        $ReviewerNote = "reports\reviewer-report.md shows Verdict: " + $Matches[1]
    }
}

$AuditNote = "reports\dependency-audit.md was not found."
if (Test-Path $AuditReportPath) {
    $AuditNote = "reports\dependency-audit.md exists and was inspected as supporting evidence."
}

$ReportLines = @()
$ReportLines += "# Diagnosis Report - Project 8 Daily Dependency Audit Loop"
$ReportLines += ""
$ReportLines += "Generated by scripts\diagnose-failure.ps1 using ONLY progress.md,"
$ReportLines += "logs\loop.log, and the existing reports. No run was replayed and"
$ReportLines += "source-data.txt was not read."
$ReportLines += ""
$ReportLines += "## What failed?"
$ReportLines += $WhatFailed
$ReportLines += ""
$ReportLines += "## When did it fail?"
$ReportLines += $WhenFailed
$ReportLines += ""
$ReportLines += "## Why did it fail, if known?"
$ReportLines += $WhyFailed
$ReportLines += ("Reason recorded in the log: " + $ReasonField)
$ReportLines += ""
$ReportLines += "## Is human intervention required?"
$ReportLines += ("From log: " + $NeedsHumanFromLog)
$ReportLines += ("From progress.md: " + $NeedsHumanFromProgress)
$ReportLines += ("Overall: " + $RequiresHuman)
$ReportLines += ""
$ReportLines += "## Supporting evidence checked"
$ReportLines += $ReviewerNote
$ReportLines += $AuditNote
$ReportLines += ""
$ReportLines += "## Recommended next action"
$ReportLines += $NextActionFromProgress
$ReportLines += ""
$ReportLines += "---"
$ReportLines += "This report was built entirely from progress.md, logs\loop.log, and"
$ReportLines += "the existing reports. This is the same information you would have if"
$ReportLines += "this loop had failed overnight with nobody watching."

Set-Content -Path $DiagnosisReportPath -Value $ReportLines

Write-Host "Diagnosis complete. Report written to reports\diagnosis-report.md"
Write-Host ""
Get-Content $DiagnosisReportPath