# compare-runs.ps1
# Project 9: Rehearse a Routine for Free
#
# Compares the successful and failed transcripts and produces
# reports\comparison-report.md, showing that both runs can show a
# GREEN platform status while their actual task results differ.

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$SuccessTranscriptPath = Join-Path $ProjectRoot "transcripts\successful-run.md"
$FailureTranscriptPath = Join-Path $ProjectRoot "transcripts\failed-run.md"
$ComparisonReportPath = Join-Path $ProjectRoot "reports\comparison-report.md"

if (-not (Test-Path $SuccessTranscriptPath)) {
    Write-Host "[MISSING] transcripts\successful-run.md - run scripts\simulate-success.ps1 first."
    exit 1
}

if (-not (Test-Path $FailureTranscriptPath)) {
    Write-Host "[MISSING] transcripts\failed-run.md - run scripts\simulate-failure.ps1 first."
    exit 1
}

$SuccessText = Get-Content $SuccessTranscriptPath -Raw
$FailureText = Get-Content $FailureTranscriptPath -Raw

$SuccessPlatformStatus = "UNKNOWN"
if ($SuccessText -match "Platform Status:\s*(\S+)") {
    $SuccessPlatformStatus = $Matches[1]
}

$SuccessTaskResult = "UNKNOWN"
if ($SuccessText -match "Task Result:\s*(\S+)") {
    $SuccessTaskResult = $Matches[1]
}

$FailurePlatformStatus = "UNKNOWN"
if ($FailureText -match "Platform Status:\s*(\S+)") {
    $FailurePlatformStatus = $Matches[1]
}

$FailureTaskResult = "UNKNOWN"
if ($FailureText -match "Task Result:\s*(\S+)") {
    $FailureTaskResult = $Matches[1]
}

$ReportLines = @()
$ReportLines += "# Comparison Report"
$ReportLines += ""
$ReportLines += "Generated by scripts\compare-runs.ps1, reading only"
$ReportLines += "transcripts\successful-run.md and transcripts\failed-run.md."
$ReportLines += ""
$ReportLines += "| Item              | Successful Run          | Failed Run              |"
$ReportLines += "| ------------------ | ----------------------- | ------------------------ |"
$ReportLines += ("| Platform Status    | " + $SuccessPlatformStatus + "                    | " + $FailurePlatformStatus + "                    |")
$ReportLines += ("| Task Result        | " + $SuccessTaskResult + "                  | " + $FailureTaskResult + "                   |")
$ReportLines += "| Transcript Review  | Required                 | Required                  |"
$ReportLines += "| Actual Task        | Completed                | Failed                    |"
$ReportLines += ""
$ReportLines += "## Why status alone is insufficient"
$ReportLines += ""
$ReportLines += "Both runs above show the same Platform Status. If you only looked"
$ReportLines += "at a status color or a single word, you could not tell these two"
$ReportLines += "runs apart. The difference only appears once you actually open and"
$ReportLines += "read the transcript: one run's transcript shows a real file being"
$ReportLines += "read and a real summary being produced, and the other shows an"
$ReportLines += "attempt to read a file that does not exist, caught safely, with no"
$ReportLines += "summary ever produced."
$ReportLines += ""
$ReportLines += "## The Project 9 lesson (A5)"
$ReportLines += ""
$ReportLines += "Green status alone cannot prove that the task itself succeeded."
$ReportLines += "The transcript must be read. A green status means the session ended"
$ReportLines += "without an infrastructure error - nothing more. It does not mean the"
$ReportLines += "task you actually asked for was completed."

Set-Content -Path $ComparisonReportPath -Value $ReportLines

Write-Host "Comparison complete. Report written to reports\comparison-report.md"
Write-Host ""
Get-Content $ComparisonReportPath