# compare-gate.ps1
# Project 11: Build the Two-Routine Gate
#
# Reads the implementer and reviewer transcripts and genuinely verifies
# the gate's separation properties, then writes reports\gate-report.md.
# This does not re-run either simulation - it only inspects files
# already produced by scripts\simulate-implementer.ps1 and
# scripts\simulate-reviewer.ps1.

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$TranscriptsDir = Join-Path $ProjectRoot "transcripts"
$GateReportPath = Join-Path $ProjectRoot "reports\gate-report.md"

$IssueNumbers = @("001", "002", "003")

$AllChecksPassed = $true
$ProblemNotes = @()
$SummaryRows = @()

foreach ($IssueNumber in $IssueNumbers) {

    $ImplementerPath = Join-Path $TranscriptsDir ("implementer-run-" + $IssueNumber + ".md")
    $ReviewerPath = Join-Path $TranscriptsDir ("reviewer-run-" + $IssueNumber + ".md")

    if (-not (Test-Path -LiteralPath $ImplementerPath -PathType Leaf)) {
        $AllChecksPassed = $false
        $ProblemNotes += ("Missing implementer transcript for issue " + $IssueNumber + ". Run scripts\simulate-implementer.ps1 first.")
        continue
    }

    if (-not (Test-Path -LiteralPath $ReviewerPath -PathType Leaf)) {
        $AllChecksPassed = $false
        $ProblemNotes += ("Missing reviewer transcript for issue " + $IssueNumber + ". Run scripts\simulate-reviewer.ps1 first.")
        continue
    }

    $ImplementerText = Get-Content -LiteralPath $ImplementerPath -Raw
    $ReviewerText = Get-Content -LiteralPath $ReviewerPath -Raw

    # Check: implementer never graded itself
    if ($ImplementerText -match "Verdict:") {
        $AllChecksPassed = $false
        $ProblemNotes += ("Issue " + $IssueNumber + ": implementer transcript contains a Verdict line - it must never grade itself.")
    }

    # Check: reviewer never claims to have implemented or created a branch
    if ($ReviewerText -match "Branch created") {
        $AllChecksPassed = $false
        $ProblemNotes += ("Issue " + $IssueNumber + ": reviewer transcript claims to have created a branch - it must only review.")
    }

    # Check: neither transcript claims a merge
    if ($ImplementerText -match "(?i)merged" -or $ReviewerText -match "(?i)\bmerged\b") {
        $AllChecksPassed = $false
        $ProblemNotes += ("Issue " + $IssueNumber + ": a transcript references a merge action, which is never allowed in this gate.")
    }

    # Check: reviewer transcript records a real Verdict of PASS or FAIL
    $VerdictFound = "NONE"
    if ($ReviewerText -match "Verdict:\s*(PASS|FAIL)") {
        $VerdictFound = $Matches[1]
    }
    else {
        $AllChecksPassed = $false
        $ProblemNotes += ("Issue " + $IssueNumber + ": reviewer transcript does not contain a valid PASS/FAIL verdict.")
    }

    # Check: implementer transcript records a distinct branch name
    $BranchFound = "UNKNOWN"
    if ($ImplementerText -match "Branch name:\s*(\S+)") {
        $BranchFound = $Matches[1]
    }

    $SummaryRows += ("| " + $IssueNumber + " | " + $BranchFound + " | " + $VerdictFound + " |")
}

# Check branch names are distinct across issues (independent processing)
$BranchNames = @()
foreach ($Row in $SummaryRows) {
    $Parts = $Row -split "\|"
    if ($Parts.Count -ge 3) {
        $BranchNames += $Parts[2].Trim()
    }
}
$UniqueBranchCount = ($BranchNames | Select-Object -Unique).Count

if ($UniqueBranchCount -lt $SummaryRows.Count) {
    $AllChecksPassed = $false
    $ProblemNotes += "Branch names are not all distinct across issues - each issue must get its own branch."
}

$GateVerdict = "PASS"
if (-not $AllChecksPassed) {
    $GateVerdict = "FAIL"
}

$ReportLines = @()
$ReportLines += "# Gate Report - Two-Routine Gate (SIMULATED)"
$ReportLines += ""
$ReportLines += "Generated by scripts\compare-gate.ps1, reading the implementer and"
$ReportLines += "reviewer transcripts already on disk. This proves the complete gate"
$ReportLines += "end-to-end, using simulated data, with genuine cross-file checks."
$ReportLines += ""
$ReportLines += "## The Gate"
$ReportLines += ""
$ReportLines += "Issue"
$ReportLines += "  |"
$ReportLines += "  v"
$ReportLines += "Implementer Routine (schedule trigger)"
$ReportLines += "  |"
$ReportLines += "  v"
$ReportLines += "Own branch"
$ReportLines += "  |"
$ReportLines += "  v"
$ReportLines += "Pull Request"
$ReportLines += "  |"
$ReportLines += "  v"
$ReportLines += "Independent Reviewer Routine (pull_request trigger)"
$ReportLines += "  |"
$ReportLines += "  v"
$ReportLines += "PASS / FAIL"
$ReportLines += "  |"
$ReportLines += "  v"
$ReportLines += "NO AUTOMATIC MERGE"
$ReportLines += ""
$ReportLines += "## Per-issue results"
$ReportLines += ""
$ReportLines += "| Issue | Branch (simulated) | Reviewer Verdict |"
$ReportLines += "|-------|-----------------------|---------------------|"
foreach ($Row in $SummaryRows) {
    $ReportLines += $Row
}
$ReportLines += ""
$ReportLines += "## Genuine checks performed"
$ReportLines += ""
$ReportLines += "1. Implementer transcripts never contain a Verdict line (no self-grading)."
$ReportLines += "2. Reviewer transcripts never claim to have created a branch (no self-implementing)."
$ReportLines += "3. No transcript references a merge action anywhere."
$ReportLines += "4. Every reviewer transcript contains a valid PASS or FAIL verdict."
$ReportLines += "5. Every issue produced a distinct branch name (independent processing)."
$ReportLines += ""

if ($ProblemNotes.Count -gt 0) {
    $ReportLines += "## Problems found"
    $ReportLines += ""
    foreach ($Note in $ProblemNotes) {
        $ReportLines += ("- " + $Note)
    }
    $ReportLines += ""
}

$ReportLines += "## Verdict"
$ReportLines += ""
$ReportLines += ("GATE REHEARSAL RESULT: " + $GateVerdict)
$ReportLines += ""

if ($GateVerdict -eq "PASS") {
    $ReportLines += "The two-Routine gate, as simulated, correctly kept implementation and"
    $ReportLines += "review as two strictly separate responsibilities, driven by two"
    $ReportLines += "strictly separate triggers (schedule vs. pull_request), with no"
    $ReportLines += "automatic merge at any point."
}
else {
    $ReportLines += "One or more separation checks failed. See Problems found above, fix"
    $ReportLines += "the underlying transcripts or scripts, and re-run"
    $ReportLines += "scripts\compare-gate.ps1."
}

$ReportLines += ""
$ReportLines += "---"
$ReportLines += "NOTE: This is a local, simulated rehearsal. Connecting this pattern to"
$ReportLines += "a real repository requires two real Routines (see README.md, Real"
$ReportLines += "Routine Setup), real GitHub authentication provided only through"
$ReportLines += "environment variables, and real issues carrying the claude-fix label."

Set-Content -LiteralPath $GateReportPath -Value $ReportLines

Write-Host "Gate comparison complete. Report written to reports\gate-report.md"
Write-Host ""
Write-Host ("GATE REHEARSAL RESULT: " + $GateVerdict)

if ($GateVerdict -eq "PASS") {
    exit 0
}
else {
    exit 1
}