# compare-runs.ps1
# Project 10: The Secrets Drill
#
# Compares the .env-based failure transcript and the environment
# variable success transcript, and produces
# reports\comparison-report.md. Reads only the existing transcripts and
# routine-prompt.md - never re-runs anything and never touches .env.

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$FailureTranscriptPath = Join-Path $ProjectRoot "transcripts\failed-env-file-run.md"
$SuccessTranscriptPath = Join-Path $ProjectRoot "transcripts\successful-environment-run.md"
$PromptPath = Join-Path $ProjectRoot "routine-prompt.md"
$ComparisonReportPath = Join-Path $ProjectRoot "reports\comparison-report.md"

if (-not (Test-Path -LiteralPath $FailureTranscriptPath -PathType Leaf)) {
    Write-Host "[MISSING] transcripts\failed-env-file-run.md - run scripts\simulate-env-failure.ps1 first."
    exit 1
}

if (-not (Test-Path -LiteralPath $SuccessTranscriptPath -PathType Leaf)) {
    Write-Host "[MISSING] transcripts\successful-environment-run.md - run scripts\simulate-environment-success.ps1 first."
    exit 1
}

$FailureText = Get-Content -LiteralPath $FailureTranscriptPath -Raw
$SuccessText = Get-Content -LiteralPath $SuccessTranscriptPath -Raw

$KeyName = "OPENROUTER_API_KEY"

$FailureKeyAvailable = "NO"
if ($FailureText -match [regex]::Escape($KeyName + " = [AVAILABLE]")) {
    $FailureKeyAvailable = "YES"
}

$SuccessKeyAvailable = "NO"
if ($SuccessText -match [regex]::Escape($KeyName + " = [AVAILABLE]")) {
    $SuccessKeyAvailable = "YES"
}

$FailureTaskResult = "UNKNOWN"
if ($FailureText -match "Task Result:\s*(\S+)") {
    $FailureTaskResult = $Matches[1]
}

$SuccessTaskResult = "UNKNOWN"
if ($SuccessText -match "Task Result:\s*(\S+)") {
    $SuccessTaskResult = $Matches[1]
}

$FreshCloneContainsEnv = "NO"
if ($FailureText -match "Does the simulated fresh clone contain \.env\?\s*(\S+)") {
    $FreshCloneContainsEnv = $Matches[1]
}

# Check whether the required prompt instruction actually exists in
# routine-prompt.md, rather than assuming it does.
$PromptPreventsEnvLookup = "NO"
if (Test-Path -LiteralPath $PromptPath -PathType Leaf) {
    $PromptText = Get-Content -LiteralPath $PromptPath -Raw
    if ($PromptText -match [regex]::Escape("credentials are available as environment variables; do not look for a .env file")) {
        $PromptPreventsEnvLookup = "YES"
    }
}

# This project's scripts are designed by construction to never print a
# real secret value anywhere. This is reported as a design guarantee,
# not something re-derived from the transcript text.
$SecretExposed = "NO"

$ReportLines = @()
$ReportLines += "# Comparison Report - Secrets Drill"
$ReportLines += ""
$ReportLines += "Generated by scripts\compare-runs.ps1, reading only"
$ReportLines += "transcripts\failed-env-file-run.md,"
$ReportLines += "transcripts\successful-environment-run.md, and routine-prompt.md."
$ReportLines += ""
$ReportLines += "| Item                          | .env Run   | Environment Variable Run |"
$ReportLines += "| ------------------------------ | ---------- | ------------------------- |"
$ReportLines += "| Secret location                 | .env       | Environment variable      |"
$ReportLines += ("| Fresh clone contains .env       | " + $FreshCloneContainsEnv + "         | Not required              |")
$ReportLines += ("| Secret available                 | " + $FailureKeyAvailable + "         | " + $SuccessKeyAvailable + "                       |")
$ReportLines += ("| Task Result                      | " + $FailureTaskResult + "     | " + $SuccessTaskResult + "                   |")
$ReportLines += ("| Prompt prevents .env lookup      | NO         | " + $PromptPreventsEnvLookup + "                        |")
$ReportLines += ("| Secret exposed                    | " + $SecretExposed + "         | " + $SecretExposed + "                        |")
$ReportLines += ""
$ReportLines += "## The mechanical chain"
$ReportLines += ""
$ReportLines += ".env is gitignored"
$ReportLines += "-> gitignored files do not reach GitHub"
$ReportLines += "-> a Routine starts from a fresh clone"
$ReportLines += "-> the fresh clone does not contain .env"
$ReportLines += "-> the secret is unavailable"
$ReportLines += "-> the task fails"
$ReportLines += ""
$ReportLines += "Environment Variables panel"
$ReportLines += "-> the Routine receives the secret through the environment"
$ReportLines += "-> the prompt explicitly tells Claude not to look for .env"
$ReportLines += "-> the secret is available"
$ReportLines += "-> the task succeeds"
$ReportLines += ""
$ReportLines += "## The Project 10 lesson (A4)"
$ReportLines += ""
$ReportLines += "Secrets must go in the environment variables panel, never in a .env"
$ReportLines += "file, because .env is gitignored and a Routine's fresh clone will"
$ReportLines += "never contain it. Pairing this with an explicit prompt instruction not"
$ReportLines += "to look for a .env file removes any wasted attempt down a path that"
$ReportLines += "could never succeed. In both runs the real secret value was never"
$ReportLines += "printed - only its availability status was reported."

Set-Content -LiteralPath $ComparisonReportPath -Value $ReportLines

Write-Host "Comparison complete. Report written to reports\comparison-report.md"
Write-Host ""
Get-Content -LiteralPath $ComparisonReportPath